/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Product;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Huynh Hau
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignUpFormjLabel = new javax.swing.JLabel();
        UsernamejLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        PasswordjLabel = new javax.swing.JLabel();
        ConfirmPasswordjLabel = new javax.swing.JLabel();
        UsernamejTextField = new javax.swing.JTextField();
        PasswordjTextField = new javax.swing.JPasswordField();
        ConfirmPasswordjPasswordField = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        SignUpjButton = new javax.swing.JButton();
        CanceljButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SignUpFormjLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SignUpFormjLabel.setText("Sign Up Form");

        UsernamejLabel.setText("Username");

        PasswordjLabel.setText("Password");

        ConfirmPasswordjLabel.setText("Confirm Password");

        SignUpjButton.setText("Sign Up");
        SignUpjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpjButtonActionPerformed(evt);
            }
        });

        CanceljButton.setText("Cancel");
        CanceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanceljButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(SignUpFormjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UsernamejLabel)
                                    .addComponent(PasswordjLabel)
                                    .addComponent(ConfirmPasswordjLabel))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UsernamejTextField)
                                    .addComponent(PasswordjTextField)
                                    .addComponent(ConfirmPasswordjPasswordField)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SignUpjButton)
                                .addGap(18, 18, 18)
                                .addComponent(CanceljButton)
                                .addGap(75, 75, 75))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SignUpFormjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernamejLabel)
                    .addComponent(UsernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordjLabel)
                    .addComponent(PasswordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPasswordjLabel)
                    .addComponent(ConfirmPasswordjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignUpjButton)
                    .addComponent(CanceljButton))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpjButtonActionPerformed
      StringBuilder sb = new StringBuilder(); 
        if (UsernamejTextField.getText().equals("")){
            sb.append("Username is required! \n");
             UsernamejTextField.setBackground(Color.YELLOW);
             UsernamejTextField.requestFocus();
        }
        else{
            UsernamejTextField.setBackground(Color.WHITE);
        }
        String Password = new String(PasswordjTextField.getPassword());
        if (Password.equals("")){
            sb.append("Password is required! \n");
            PasswordjTextField.setBackground(Color.YELLOW);
            PasswordjTextField.requestFocus();
        }
        else{
            PasswordjTextField.setBackground(Color.WHITE);
        }
        String confirm = new String(ConfirmPasswordjPasswordField.getPassword());
        if (!Password.equals("")&&!Password.equals(confirm)){
            sb.append("Password and confirm password must be the same \n");
            PasswordjTextField.setBackground(Color.YELLOW);
            ConfirmPasswordjPasswordField.setBackground(Color.YELLOW);   
        }
        else{
            PasswordjTextField.setBackground(Color.WHITE);
            ConfirmPasswordjPasswordField.setBackground(Color.WHITE); 
        }
        if (sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString());
            return; 
        }
        JOptionPane.showMessageDialog(this, "Information is valid");
        //lien ket 2 form
        SignIn dangnhap = new SignIn();
        dangnhap.setVisible(true);
    }//GEN-LAST:event_SignUpjButtonActionPerformed

    private void CanceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanceljButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CanceljButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CanceljButton;
    private javax.swing.JLabel ConfirmPasswordjLabel;
    private javax.swing.JPasswordField ConfirmPasswordjPasswordField;
    private javax.swing.JLabel PasswordjLabel;
    private javax.swing.JPasswordField PasswordjTextField;
    private javax.swing.JLabel SignUpFormjLabel;
    private javax.swing.JButton SignUpjButton;
    private javax.swing.JLabel UsernamejLabel;
    private javax.swing.JTextField UsernamejTextField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
